### PR TITLE
Update LoadedImage.py

### PR DESCRIPTION
**Pull request by cleansely**
Incorrect use of "(" and "["

### CODE REVIEW

**Comment by cleansely** [comment]
machine translation:
In python3.7, the following errors will appear
```
  File "/Users/ly/opt/miniconda3/envs/py37/lib/python3.7/site-packages/depixlib/LoadedImage.py", line 33, in __loadImageData
    return cast(list[list[tuple[int, int, int]]], _imageData)
TypeError: 'type' object is not subscriptable
```
I mistakenly thought it was the problem of brackets, so I modified it, and then it can run normally in python3.7

**Comment by DwyaneLe** [comment]
u r right

**Comment by HaolunWang** [comment]
Did you get error like "return cast(list(list(tuple(int, int, int))), _imageData) **TypeError: tuple expected at most 1 argument, got 3**" in the same place? Is it because of image size's big?

**Comment by SheriffRabbit** [comment]
Chinese words need to parse the diagram
we also need a feature that generates parsing diagrams

**Pull request closed without merging**
